regen

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -13203,42 +13203,56 @@ fi
 
 
 
-if test "${ac_cv_sizeof_unsigned_int}" = "4"; then
+if test "${ac_cv_sizeof_unsigned_short}" = "4"; then
 	cat >>confdefs.h <<\_ACEOF
-#define A_UINT32_T unsigned int
+#define A_UINT32_T unsigned short
 _ACEOF
 
 else
-	if test "${ac_cv_sizeof_unsigned_long}" = "4"; then
+	if test "${ac_cv_sizeof_unsigned_int}" = "4"; then
 		cat >>confdefs.h <<\_ACEOF
-#define A_UINT32_T unsigned long
+#define A_UINT32_T unsigned int
 _ACEOF
 
 	else
-		{ { echo "$as_me:$LINENO: error: CHECK_TYPE_uint32_t - please report to lame-dev@lists.sourceforge.net" >&5
+		if test "${ac_cv_sizeof_unsigned_long}" = "4"; then
+			cat >>confdefs.h <<\_ACEOF
+#define A_UINT32_T unsigned long
+_ACEOF
+
+		else
+			{ { echo "$as_me:$LINENO: error: CHECK_TYPE_uint32_t - please report to lame-dev@lists.sourceforge.net" >&5
 echo "$as_me: error: CHECK_TYPE_uint32_t - please report to lame-dev@lists.sourceforge.net" >&2;}
    { (exit 1); exit 1; }; }
+		fi
 	fi
 fi
 
 
 
 
-if test "${ac_cv_sizeof_int}" = "4"; then
+if test "${ac_cv_sizeof_short}" = "4"; then
 	cat >>confdefs.h <<\_ACEOF
-#define A_INT32_T int
+#define A_INT32_T short
 _ACEOF
 
 else
-	if test "${ac_cv_sizeof_long}" = "4"; then
+	if test "${ac_cv_sizeof_int}" = "4"; then
 		cat >>confdefs.h <<\_ACEOF
-#define A_INT32_T long
+#define A_INT32_T int
 _ACEOF
 
 	else
-		{ { echo "$as_me:$LINENO: error: CHECK_TYPE_int32_t - please report to lame-dev@lists.sourceforge.net" >&5
+		if test "${ac_cv_sizeof_long}" = "4"; then
+			cat >>confdefs.h <<\_ACEOF
+#define A_INT32_T long
+_ACEOF
+
+		else
+			{ { echo "$as_me:$LINENO: error: CHECK_TYPE_int32_t - please report to lame-dev@lists.sourceforge.net" >&5
 echo "$as_me: error: CHECK_TYPE_int32_t - please report to lame-dev@lists.sourceforge.net" >&2;}
    { (exit 1); exit 1; }; }
+		fi
 	fi
 fi
 
@@ -14051,6 +14065,95 @@ _ACEOF
 fi
 done
 
+if test $ac_cv_func_socket = no; then
+	# maybe it is in libsocket
+	echo "$as_me:$LINENO: checking for socket in -lsocket" >&5
+echo $ECHO_N "checking for socket in -lsocket... $ECHO_C" >&6
+if test "${ac_cv_lib_socket_socket+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lsocket  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char socket ();
+#ifdef F77_DUMMY_MAIN
+#  ifdef __cplusplus
+     extern "C"
+#  endif
+   int F77_DUMMY_MAIN() { return 1; }
+#endif
+int
+main ()
+{
+socket ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_socket_socket=yes
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+ac_cv_lib_socket_socket=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_socket_socket" >&5
+echo "${ECHO_T}$ac_cv_lib_socket_socket" >&6
+if test $ac_cv_lib_socket_socket = yes; then
+  cat >>confdefs.h <<\_ACEOF
+#define HAVE_SOCKET 1
+_ACEOF
+
+		LIBS="$LIBS -lsocket"
+fi
+
+
+	if test "X${ac_cv_lib_socket_socket}" != "Xyes"; then
+		{ { echo "$as_me:$LINENO: error: function socket is mandatory" >&5
+echo "$as_me: error: function socket is mandatory" >&2;}
+   { (exit 1); exit 1; }; }
+	else
+		case ${host_os} in
+		*solaris*)
+			LIBS="$LIBS -lnsl"
+			;;
+		esac
+	fi
+fi
+
+if test "X${ac_cv_func_strtol}" != "Xyes"; then
+	{ { echo "$as_me:$LINENO: error: function strtol is mandatory" >&5
+echo "$as_me: error: function strtol is mandatory" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test "X${ac_cv_func_gettimeofday}" != "Xyes"; then
+	{ { echo "$as_me:$LINENO: error: function strtol is mandatory" >&5
+echo "$as_me: error: function strtol is mandatory" >&2;}
+   { (exit 1); exit 1; }; }
+fi
 
 
 CFLAGS=${CFLAGS}
@@ -15693,13 +15796,29 @@ if test "x$GCC" = "xyes"; then
 			-fforce-mem"
         	;;
 	3.0*)
+		# -funroll-loops seems to produce buggy code with gcc 3.0.3
 		OPTIMIZATION="-O -fomit-frame-pointer -ffast-math"
+			OPTIMIZATION_FULL="-fmove-all-movables -freduce-all-givs \
+			-fbranch-count-reg -fforce-addr -fforce-mem"
+		;;
+	3.2*)
+		# -fomit-frame-pointer seems to be buggy on cygwin
+		case ${host_os} in
+		*cygwin*)
+			OMIT_FRAME_POINTER=
+			;;
+		*)
+			OMIT_FRAME_POINTER=-fomit-frame-pointer
+			;;
+		esac
+
+		OPTIMIZATION="-O ${OMIT_FRAME_POINTER} -ffast-math"
 		OPTIMIZATION_FULL="-fmove-all-movables -freduce-all-givs \
 			-fbranch-count-reg -fforce-addr -fforce-mem"
 		;;
 	*)
 		# default
-		OPTIMIZATION="-O3 -fomit-frame-pointer -ffast-math \
+		OPTIMIZATION="-O3 ${OMIT_FRAME_POINTER} -ffast-math \
 			-funroll-loops"
 		OPTIMIZATION_FULL="-fmove-all-movables -freduce-all-givs \
 				-fbranch-count-reg -fforce-addr -fforce-mem"
