regen

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -10241,8 +10241,7 @@ fi
 
 
 
-
-for ac_func in gettimeofday socket strtol
+for ac_func in gettimeofday strtol
 do
 as_ac_var=`echo "ac_cv_func_$ac_func" | $as_tr_sh`
 echo "$as_me:$LINENO: checking for $ac_func" >&5
@@ -10317,9 +10316,204 @@ _ACEOF
 fi
 done
 
-if test $ac_cv_func_socket = no; then
-	# maybe it is in libsocket
-	echo "$as_me:$LINENO: checking for socket in -lsocket" >&5
+
+if test "X${ac_cv_func_strtol}" != "Xyes"; then
+	{ { echo "$as_me:$LINENO: error: function strtol is mandatory" >&5
+echo "$as_me: error: function strtol is mandatory" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+SOCKETFUNCTION=YES
+if test "${ac_cv_header_winsock2_h+set}" = set; then
+  echo "$as_me:$LINENO: checking for winsock2.h" >&5
+echo $ECHO_N "checking for winsock2.h... $ECHO_C" >&6
+if test "${ac_cv_header_winsock2_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header_winsock2_h" >&5
+echo "${ECHO_T}$ac_cv_header_winsock2_h" >&6
+else
+  # Is the header compilable?
+echo "$as_me:$LINENO: checking winsock2.h usability" >&5
+echo $ECHO_N "checking winsock2.h usability... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+$ac_includes_default
+#include <winsock2.h>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+ac_header_compiler=no
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6
+
+# Is the header present?
+echo "$as_me:$LINENO: checking winsock2.h presence" >&5
+echo $ECHO_N "checking winsock2.h presence... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+#include <winsock2.h>
+_ACEOF
+if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
+  (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
+  ac_status=$?
+  egrep -v '^ *\+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null; then
+  if test -s conftest.err; then
+    ac_cpp_err=$ac_c_preproc_warn_flag
+  else
+    ac_cpp_err=
+  fi
+else
+  ac_cpp_err=yes
+fi
+if test -z "$ac_cpp_err"; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  ac_header_preproc=no
+fi
+rm -f conftest.err conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc in
+  yes:no )
+    { echo "$as_me:$LINENO: WARNING: winsock2.h: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: winsock2.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: winsock2.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: winsock2.h: proceeding with the preprocessor's result" >&2;};;
+  no:yes )
+    { echo "$as_me:$LINENO: WARNING: winsock2.h: present but cannot be compiled" >&5
+echo "$as_me: WARNING: winsock2.h: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: winsock2.h: check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: winsock2.h: check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: winsock2.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: winsock2.h: proceeding with the preprocessor's result" >&2;};;
+esac
+echo "$as_me:$LINENO: checking for winsock2.h" >&5
+echo $ECHO_N "checking for winsock2.h... $ECHO_C" >&6
+if test "${ac_cv_header_winsock2_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_header_winsock2_h=$ac_header_preproc
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header_winsock2_h" >&5
+echo "${ECHO_T}$ac_cv_header_winsock2_h" >&6
+
+fi
+if test $ac_cv_header_winsock2_h = yes; then
+  cat >>confdefs.h <<\_ACEOF
+#define HAVE_WINSOCKET 1
+_ACEOF
+
+		LIBS="$LIBS -lwsock32"
+fi
+
+
+if test $ac_cv_header_winsock2_h = no; then
+
+for ac_func in socket
+do
+as_ac_var=`echo "ac_cv_func_$ac_func" | $as_tr_sh`
+echo "$as_me:$LINENO: checking for $ac_func" >&5
+echo $ECHO_N "checking for $ac_func... $ECHO_C" >&6
+if eval "test \"\${$as_ac_var+set}\" = set"; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+/* System header to define __stub macros and hopefully few prototypes,
+    which can conflict with char $ac_func (); below.  */
+#include <assert.h>
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char $ac_func ();
+char (*f) ();
+
+#ifdef F77_DUMMY_MAIN
+#  ifdef __cplusplus
+     extern "C"
+#  endif
+   int F77_DUMMY_MAIN() { return 1; }
+#endif
+int
+main ()
+{
+/* The GNU C library defines this for functions which it implements
+    to always fail with ENOSYS.  Some functions are actually named
+    something starting with __ and the normal name is an alias.  */
+#if defined (__stub_$ac_func) || defined (__stub___$ac_func)
+choke me
+#else
+f = $ac_func;
+#endif
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  eval "$as_ac_var=yes"
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+eval "$as_ac_var=no"
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_var'}'`" >&5
+echo "${ECHO_T}`eval echo '${'$as_ac_var'}'`" >&6
+if test `eval echo '${'$as_ac_var'}'` = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define `echo "HAVE_$ac_func" | $as_tr_cpp` 1
+_ACEOF
+
+fi
+done
+
+	if test $ac_cv_func_socket = no; then
+		# maybe it is in libsocket
+		echo "$as_me:$LINENO: checking for socket in -lsocket" >&5
 echo $ECHO_N "checking for socket in -lsocket... $ECHO_C" >&6
 if test "${ac_cv_lib_socket_socket+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -10379,32 +10573,20 @@ if test $ac_cv_lib_socket_socket = yes; then
 #define HAVE_SOCKET 1
 _ACEOF
 
-		LIBS="$LIBS -lsocket"
+			LIBS="$LIBS -lsocket"
 fi
 
 
-	if test "X${ac_cv_lib_socket_socket}" != "Xyes"; then
-		{ { echo "$as_me:$LINENO: error: function socket is mandatory" >&5
-echo "$as_me: error: function socket is mandatory" >&2;}
-   { (exit 1); exit 1; }; }
-	else
-		case ${host_os} in
-		*solaris*)
-			LIBS="$LIBS -lnsl"
-			;;
-		esac
+		if test "X${ac_cv_lib_socket_socket}" != "Xyes"; then
+			SOCKETFUNCTION=NO
+		else
+			case ${host_os} in
+			*solaris*)
+				LIBS="$LIBS -lnsl"
+				;;
+			esac
+		fi
 	fi
-fi
-
-if test "X${ac_cv_func_strtol}" != "Xyes"; then
-	{ { echo "$as_me:$LINENO: error: function strtol is mandatory" >&5
-echo "$as_me: error: function strtol is mandatory" >&2;}
-   { (exit 1); exit 1; }; }
-fi
-if test "X${ac_cv_func_gettimeofday}" != "Xyes"; then
-	{ { echo "$as_me:$LINENO: error: function strtol is mandatory" >&5
-echo "$as_me: error: function strtol is mandatory" >&2;}
-   { (exit 1); exit 1; }; }
 fi
 
 
@@ -11465,13 +11647,13 @@ cat >>confdefs.h <<\_ACEOF
 #define HAVE_EFENCE 1
 _ACEOF
 
-		echo "$as_me:$LINENO: result: \"${CONFIG_EFENCE}\"" >&5
-echo "${ECHO_T}\"${CONFIG_EFENCE}\"" >&6
+		echo "$as_me:$LINENO: result: ${CONFIG_EFENCE}" >&5
+echo "${ECHO_T}${CONFIG_EFENCE}" >&6
 	fi
 	;;
 no)
-	echo "$as_me:$LINENO: result: \"${CONFIG_EFENCE}\"" >&5
-echo "${ECHO_T}\"${CONFIG_EFENCE}\"" >&6
+	echo "$as_me:$LINENO: result: ${CONFIG_EFENCE}" >&5
+echo "${ECHO_T}${CONFIG_EFENCE}" >&6
 	;;
 *)
 	{ { echo "$as_me:$LINENO: error: bad value »${CONFIG_EFENCE}« for efence option" >&5
@@ -11719,6 +11901,11 @@ else
   WITH_MP3RTP=no
 fi;
 if test "x${WITH_MP3RTP}" = "xyes"; then
+	if test ${SOCKETFUNCTION} = NO; then
+		{ { echo "$as_me:$LINENO: error: function socket is mandatory for mp3rtp" >&5
+echo "$as_me: error: function socket is mandatory for mp3rtp" >&2;}
+   { (exit 1); exit 1; }; }
+	fi
 	WITH_MP3RTP=mp3rtp${ac_exeext}
 	echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
